### ISSUE TITLE
Mark as Paid/Recieved

### ISSUE THREAD

**Issue by pratikagarwala** [amanv8060/Coupan-System#6]
It's better to give only the dealer to mark as paid for a transaction because allowing electrician to mark as received will create hotchpotch because it will be very common among them to mark as paid without receiving cash and creating a mess. Same applies for the transaction between dealers and admin

Please call me if any queries or you have any reason for keeping this feature.

**Comment by amanv8060** [comment]
Done in Electrician app

**Comment by amanv8060** [comment]
Done in Dealer App
